# Generated by Django 5.0.14 on 2026-03-03 06:52

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('FLOOD', 'Flood'), ('ROAD_CLOSURE', 'Road closure'), ('CONSTRUCTION', 'Construction'), ('POLICE_NAKA', 'Police naka'), ('PROTEST', 'Protest'), ('HAZARD', 'Hazard'), ('OTHER', 'Other')], max_length=32)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('address_text', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('photo', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('confidence', models.IntegerField(default=20)),
                ('confirmation_count', models.IntegerField(default=0)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
